
package it.eng.projectwork.wsdl.auction_01;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuctionService", targetNamespace = "http://it/eng/projectwork/wsdl/auction_01", wsdlLocation = "file:/C:/deveng/progetti/book/projectwork/projectwork-ws/src/main/resources/META-INF/wsdl/auction_services_01.01.wsdl")
public class AuctionService_Service
    extends Service
{

    private final static URL AUCTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUCTIONSERVICE_EXCEPTION;
    private final static QName AUCTIONSERVICE_QNAME = new QName("http://it/eng/projectwork/wsdl/auction_01", "AuctionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/deveng/progetti/book/projectwork/projectwork-ws/src/main/resources/META-INF/wsdl/auction_services_01.01.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUCTIONSERVICE_WSDL_LOCATION = url;
        AUCTIONSERVICE_EXCEPTION = e;
    }

    public AuctionService_Service() {
        super(__getWsdlLocation(), AUCTIONSERVICE_QNAME);
    }

    public AuctionService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUCTIONSERVICE_QNAME, features);
    }

    public AuctionService_Service(URL wsdlLocation) {
        super(wsdlLocation, AUCTIONSERVICE_QNAME);
    }

    public AuctionService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUCTIONSERVICE_QNAME, features);
    }

    public AuctionService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuctionService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuctionService
     */
    @WebEndpoint(name = "auctionservicePort")
    public AuctionService getAuctionservicePort() {
        return super.getPort(new QName("http://it/eng/projectwork/wsdl/auction_01", "auctionservicePort"), AuctionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuctionService
     */
    @WebEndpoint(name = "auctionservicePort")
    public AuctionService getAuctionservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://it/eng/projectwork/wsdl/auction_01", "auctionservicePort"), AuctionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUCTIONSERVICE_EXCEPTION!= null) {
            throw AUCTIONSERVICE_EXCEPTION;
        }
        return AUCTIONSERVICE_WSDL_LOCATION;
    }

}
