
package it.eng.projectwork.wsdl.auction_01;

import javax.xml.ws.WebFault;
import it.eng.projectwork.xsd.auction_01.FaultMessageType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "faultMessageType", targetNamespace = "http://it/eng/projectwork/xsd/auction_01")
public class AuctionFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultMessageType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AuctionFault(String message, FaultMessageType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AuctionFault(String message, FaultMessageType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.eng.projectwork.xsd.auction_01.FaultMessageType
     */
    public FaultMessageType getFaultInfo() {
        return faultInfo;
    }

}
