
package it.eng.projectwork.wsdl.auction_01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import it.eng.projectwork.xsd.auction_01.CreateAuctionRequestType;
import it.eng.projectwork.xsd.auction_01.CreateAuctionResponseType;
import it.eng.projectwork.xsd.auction_01.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuctionService", targetNamespace = "http://it/eng/projectwork/wsdl/auction_01")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuctionService {


    /**
     * 
     * @param parameter
     * @return
     *     returns it.eng.projectwork.xsd.auction_01.CreateAuctionResponseType
     * @throws AuctionFault
     */
    @WebMethod(action = "http://it/eng/projectwork/wsdl/auction_01/createAuction")
    @WebResult(name = "createAuctionResponseType", targetNamespace = "http://it/eng/projectwork/xsd/auction_01", partName = "parameter")
    public CreateAuctionResponseType createAuction(
        @WebParam(name = "createAuctionRequestType", targetNamespace = "http://it/eng/projectwork/xsd/auction_01", partName = "parameter")
        CreateAuctionRequestType parameter)
        throws AuctionFault
    ;

}
